"""The InvariantQL domain: standard-library-only value objects and rules."""

from invariantql.domain.capabilities import EngineCapabilities, PushdownCapabilities, Support
from invariantql.domain.credentials import CredentialRef, SecretOptions
from invariantql.domain.diagnostics import (
    AdapterError,
    Diagnostic,
    DiagnosticCode,
    ExecutionError,
    InvariantQLError,
    MaterializationLimitError,
    MissingDependencyError,
    ParameterError,
    PlanValidationError,
    RegistryError,
    Severity,
    SourceError,
    SqlFrontendError,
    StagingRequiredError,
    StorageError,
    UnsupportedOperationError,
)
from invariantql.domain.execution import (
    ExecutionPlan,
    PushedOperations,
    ResidualOperations,
    check_completeness,
)
from invariantql.domain.explain import Disposition, ExecutionLocation, ExplainNode, ExplainPlan
from invariantql.domain.expressions import (
    Alias,
    And,
    Arithmetic,
    ArithmeticOp,
    Column,
    Comparison,
    ComparisonOp,
    Expression,
    ExpressionKind,
    In,
    IsNull,
    Like,
    Literal,
    Not,
    Or,
    Parameter,
)
from invariantql.domain.formats import (
    CsvFormat,
    DataFormat,
    DeltaFormat,
    IcebergFormat,
    JsonFormat,
    ParquetFormat,
    XmlFormat,
)
from invariantql.domain.location import Location
from invariantql.domain.plan import Filter, Limit, PlanNode, Project, QueryPlan, Scan, SourceRef
from invariantql.domain.schema import Field, Schema
from invariantql.domain.types import (
    BinaryType,
    BooleanType,
    DataType,
    DateType,
    DecimalType,
    FloatType,
    IntegerType,
    ListType,
    NullType,
    StringType,
    StructType,
    TimestampType,
    UnknownType,
)

__all__ = [
    "AdapterError",
    "Alias",
    "And",
    "Arithmetic",
    "ArithmeticOp",
    "BinaryType",
    "BooleanType",
    "Column",
    "Comparison",
    "ComparisonOp",
    "CredentialRef",
    "CsvFormat",
    "DataFormat",
    "DataType",
    "DateType",
    "DecimalType",
    "DeltaFormat",
    "Diagnostic",
    "DiagnosticCode",
    "Disposition",
    "EngineCapabilities",
    "ExecutionError",
    "ExecutionLocation",
    "ExecutionPlan",
    "ExplainNode",
    "ExplainPlan",
    "Expression",
    "ExpressionKind",
    "Field",
    "Filter",
    "FloatType",
    "IcebergFormat",
    "In",
    "IntegerType",
    "InvariantQLError",
    "IsNull",
    "JsonFormat",
    "Like",
    "Limit",
    "ListType",
    "Literal",
    "Location",
    "MaterializationLimitError",
    "MissingDependencyError",
    "Not",
    "NullType",
    "Or",
    "Parameter",
    "ParameterError",
    "ParquetFormat",
    "PlanNode",
    "PlanValidationError",
    "Project",
    "PushdownCapabilities",
    "PushedOperations",
    "QueryPlan",
    "RegistryError",
    "ResidualOperations",
    "Scan",
    "Schema",
    "SecretOptions",
    "Severity",
    "SourceError",
    "SourceRef",
    "SqlFrontendError",
    "StagingRequiredError",
    "StorageError",
    "StringType",
    "StructType",
    "Support",
    "TimestampType",
    "UnknownType",
    "UnsupportedOperationError",
    "XmlFormat",
    "check_completeness",
]
